openapi: 3.0.3
info:
  title: Eugepet (IVARE)
  version: 1.0.0
  description: "API RESTful feita com Django REST Framework para gerenciamento de
    vacinas de pets.\n\n Níveis de acessoo:\n    \n\n- **Administradores**: Acesso
    total aos endpoints do sistema\n    \n\n- **Veterinários**: Gerenciamento de pets,
    tutores, vacinas e registros\n    \n\n- **Tutores**: Visualização dos próprios
    dados e de seus pets\n    "
paths:
  /api/v1/accounts/:
    get:
      operationId: v1_accounts_list
      description: Requer permissão de administrador. Lista todods os usuários.
      summary: Listar usuários
      tags:
      - accounts
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserWGroups'
          description: ''
  /api/v1/accounts/logout/:
    post:
      operationId: v1_accounts_logout_create
      description: Remove ambos os tokens dos cookies
      summary: Remover tokens JWT
      tags:
      - accounts
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sucesso'
          description: ''
  /api/v1/accounts/token/:
    post:
      operationId: v1_accounts_token_create
      description: Recebe as credenciais do usuário e retorna os JWT tokens por meio
        de HTTPOnly cookies
      summary: Fazer login
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginRequestRequest'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWGroups'
          description: Login bem sucedido
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FalhaLogin'
          description: Falha na autenticação
  /api/v1/accounts/token/refresh/:
    post:
      operationId: v1_accounts_token_refresh_create
      description: Recebe o refresh_token por meio dos cookies HTTPOnly e atualiza
        ambos os tokens.
      summary: Atualizar tokens JWT
      tags:
      - accounts
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWGroups'
          description: Tokens atualizados com sucesso. Novos tokens enviados via cookies
            HTTPOnly.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefreshError'
          description: ''
  /api/v1/pets/:
    get:
      operationId: v1_pets_list
      description: Veterinários veem todos. Tutores veem apenas seus pets.
      summary: Listagem de pets
      parameters:
      - in: query
        name: tutor
        schema:
          type: integer
        description: Para visualizar os pets de um tutor especifico
      tags:
      - pets
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PetList'
          description: ''
    post:
      operationId: v1_pets_create
      description: Requer permissão de veterinário.
      summary: Cadastrar novo pet
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDetails'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
  /api/v1/pets/{id}/:
    get:
      operationId: v1_pets_retrieve
      description: Retorna informações detalhadas de um pet específico, incluindo
        dados completos do tutor.
      summary: Obter detalhes de um pet
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este pet.
        required: true
      tags:
      - pets
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDetails'
          description: ''
    put:
      operationId: v1_pets_update
      description: Requer permissão de veterinário.
      summary: Atualizar pet (completo)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este pet.
        required: true
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDetails'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    patch:
      operationId: v1_pets_partial_update
      description: Requer permissão de veterinário.
      summary: Atualizar pet (parcial)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este pet.
        required: true
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPetCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPetCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPetCreateRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDetails'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    delete:
      operationId: v1_pets_destroy
      description: Requer permissão de administrador.
      summary: Deletar pet
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este pet.
        required: true
      tags:
      - pets
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/tutores/:
    get:
      operationId: v1_tutores_list
      description: Requer permissão de veterinário.
      summary: Listagem de tutores
      tags:
      - tutores
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tutor'
          description: ''
    post:
      operationId: v1_tutores_create
      description: Apenas o veterinário pode cadastar um novo tutor. Envia todos os
        dados do user caso queira criar um, ou apenas o user_id caso já exista.
      summary: Cadastrar novo tutor
      tags:
      - tutores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TutorCreateRequest'
            examples:
              CriandoNovoUsuário:
                value:
                  username: maria
                  first_name: Maria
                  last_name: Santos
                  email: maria@gmail.com
                  password: senha123
                  celular: '12345958901'
                  cpf: '78570651023'
                summary: Criando novo usuário
                description: Cria um novo usuário junto com o tutor
              UsandoUsuárioExistente:
                value:
                  user_id: 3
                  celular: '12345958901'
                  cpf: '78570651023'
                summary: Usando usuário existente
                description: Associa um usuário já existe como tutor
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TutorCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TutorCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutor'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
  /api/v1/tutores/{id}/:
    get:
      operationId: v1_tutores_retrieve
      description: Requer permissão de veterinário, ou ser o próprio tutor.
      summary: Obter detalhes do tutor
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Tutor.
        required: true
      tags:
      - tutores
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutor'
          description: ''
    put:
      operationId: v1_tutores_update
      description: Requer permissão de veterinário.
      summary: Atualizar tutor (completo)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Tutor.
        required: true
      tags:
      - tutores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TutorRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TutorRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TutorRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutor'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    patch:
      operationId: v1_tutores_partial_update
      description: Requer permissão de veterinário.
      summary: Atualizar tutor (parcial)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Tutor.
        required: true
      tags:
      - tutores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTutorRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTutorRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTutorRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tutor'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    delete:
      operationId: v1_tutores_destroy
      description: Requer permissão de veterinário.
      summary: Deletar tutor
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Tutor.
        required: true
      tags:
      - tutores
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/vacinas/registros/:
    get:
      operationId: v1_vacinas_registros_list
      description: "\n        Lista registros de vacinação aplicadas em pets.\n        \n
        \       Filtros:\n        - `pet`: ID do pet para filtrar registros\n        -
        `veterinario`: ID do veterinário para filtrar registros\n        \n        Regras
        de acesso:\n        - Veterinários: visualizam todos os registros\n        -
        Tutores: visualizam apenas registros de seus pets\n        "
      summary: Listagem de registros de vacinação
      parameters:
      - in: query
        name: pet
        schema:
          type: integer
        description: Filtrar registros por ID do pet
      - in: query
        name: veterinario
        schema:
          type: integer
        description: Filtrar registros por ID do veterinário
      tags:
      - registros
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegistroVacinaList'
          description: ''
    post:
      operationId: v1_vacinas_registros_create
      description: Cria um novo registro de vacinação aplicada em um pet. Requer permissão
        de veterinário ou tutor.
      summary: Registrar vacinação
      tags:
      - registros
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroVacinaDetails'
          description: ''
  /api/v1/vacinas/registros/{id}/:
    get:
      operationId: v1_vacinas_registros_retrieve
      description: Retorna informações detalhadas de um registro de vacinação específico.
      summary: Obter detalhes do registro de vacinação
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este registro vacina.
        required: true
      tags:
      - registros
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroVacinaDetails'
          description: ''
    put:
      operationId: v1_vacinas_registros_update
      description: Requer permissão de veterinário ou tutor.
      summary: Atualizar registro de vacinação (completo)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este registro vacina.
        required: true
      tags:
      - registros
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegistroVacinaCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroVacinaCreate'
          description: ''
    patch:
      operationId: v1_vacinas_registros_partial_update
      description: Requer permissão de veterinário ou tutor.
      summary: Atualizar registro de vacinação (parcial)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este registro vacina.
        required: true
      tags:
      - registros
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRegistroVacinaCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRegistroVacinaCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRegistroVacinaCreateRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistroVacinaCreate'
          description: ''
    delete:
      operationId: v1_vacinas_registros_destroy
      description: Requer permissão de veterinário ou tutor.
      summary: Deletar registro de vacinação
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este registro vacina.
        required: true
      tags:
      - registros
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/vacinas/unidades/:
    get:
      operationId: v1_vacinas_unidades_list
      description: Requer permissão de veterinário. Lista todas as unidades de vacinas
        disponíveis no sistema.
      summary: Listagem de vacinas
      tags:
      - vacinas
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vacina'
          description: ''
    post:
      operationId: v1_vacinas_unidades_create
      description: Requer permissão de veterinário. Cria uma nova unidade de vacina.
      summary: Cadastrar nova vacina
      tags:
      - vacinas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacina'
          description: ''
  /api/v1/vacinas/unidades/{id}/:
    get:
      operationId: v1_vacinas_unidades_retrieve
      description: Requer permissão de veterinário.
      summary: Obter detalhes da vacina
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este vacina.
        required: true
      tags:
      - vacinas
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacina'
          description: ''
    put:
      operationId: v1_vacinas_unidades_update
      description: Requer permissão de veterinário.
      summary: Atualizar vacina (completo)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este vacina.
        required: true
      tags:
      - vacinas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VacinaRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacina'
          description: ''
    patch:
      operationId: v1_vacinas_unidades_partial_update
      description: Requer permissão de veterinário.
      summary: Atualizar vacina (parcial)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este vacina.
        required: true
      tags:
      - vacinas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedVacinaRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedVacinaRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedVacinaRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacina'
          description: ''
    delete:
      operationId: v1_vacinas_unidades_destroy
      description: Requer permissão de veterinário.
      summary: Deletar vacina
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este vacina.
        required: true
      tags:
      - vacinas
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/veterinarios/:
    get:
      operationId: v1_veterinarios_list
      description: Requer permissão de veterinário.
      summary: Listagem de veterinários
      tags:
      - veterinarios
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VeterinarioBasic'
          description: ''
    post:
      operationId: v1_veterinarios_create
      description: Requer permissão de administrador. Envia todos os dados do user
        caso queira criar um, ou apenas o user_id caso já exista.
      summary: Cadastrar novo veterinário
      tags:
      - veterinarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioCreateRequest'
            examples:
              CriandoNovoUsuário:
                value:
                  username: maria
                  first_name: Maria
                  last_name: Santos
                  email: maria@gmail.com
                  password: senha123
                  celular: '12345958901'
                  cpf: '78570651023'
                  crmv: '123456'
                summary: Criando novo usuário
                description: Cria um novo usuário junto com o veterinário
              UsandoUsuárioExistente:
                value:
                  user_id: 3
                  celular: '12345958901'
                  cpf: '78570651023'
                  crmv: '123456'
                summary: Usando usuário existente
                description: Associa um usuário já existe como veterinário
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VeterinarioCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VeterinarioCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veterinario'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
  /api/v1/veterinarios/{id}/:
    get:
      operationId: v1_veterinarios_retrieve
      description: Requer permissão de veterinário.
      summary: Obter detalhes do veterinário
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este veterinario.
        required: true
      tags:
      - veterinarios
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veterinario'
          description: ''
    put:
      operationId: v1_veterinarios_update
      description: O usuário deve ser o próprio veterinário.
      summary: Atualizar veterinário (completo)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este veterinario.
        required: true
      tags:
      - veterinarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeterinarioRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VeterinarioRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VeterinarioRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veterinario'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    patch:
      operationId: v1_veterinarios_partial_update
      description: O usuário deve ser o próprio veterinário.
      summary: Atualizar veterinário (parcial)
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este veterinario.
        required: true
      tags:
      - veterinarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedVeterinarioRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedVeterinarioRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedVeterinarioRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veterinario'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name:
                  - Erro 1
                  - Erro 2
                  another_field:
                  - Outro erro
          description: Erro de validação. Retorna um objeto onde cada chave é o nome
            do campo e o valor é uma lista de mensagens de erro.
    delete:
      operationId: v1_veterinarios_destroy
      description: Request permissão de administrador
      summary: Deletar veterinário
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este veterinario.
        required: true
      tags:
      - veterinarios
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    FalhaLogin:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    LoginRequestRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - password
      - username
    PatchedPetCreateRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
          maxLength: 100
        tutor:
          type: integer
        especie:
          type: string
          minLength: 1
          maxLength: 50
        raca:
          type: string
          nullable: true
          maxLength: 100
        data_nascimento:
          type: string
          format: date
          nullable: true
    PatchedRegistroVacinaCreateRequest:
      type: object
      properties:
        veterinario:
          type: integer
        vacina:
          type: integer
        pet:
          type: integer
        observacoes:
          type: string
        data:
          type: string
          format: date
    PatchedTutorRequest:
      type: object
      properties:
        celular:
          type: string
          minLength: 1
          maxLength: 20
        cpf:
          type: string
          nullable: true
          minLength: 1
          maxLength: 11
    PatchedVacinaRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
          maxLength: 120
    PatchedVeterinarioRequest:
      type: object
      properties:
        celular:
          type: string
          minLength: 1
          maxLength: 20
        crmv:
          type: string
          nullable: true
          minLength: 1
          maxLength: 20
        cpf:
          type: string
          nullable: true
          minLength: 1
          maxLength: 11
    PetBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
      required:
      - id
      - nome
    PetCreateRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
          maxLength: 100
        tutor:
          type: integer
        especie:
          type: string
          minLength: 1
          maxLength: 50
        raca:
          type: string
          nullable: true
          maxLength: 100
        data_nascimento:
          type: string
          format: date
          nullable: true
      required:
      - especie
      - nome
      - tutor
    PetDetails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        tutor:
          allOf:
          - $ref: '#/components/schemas/Tutor'
          readOnly: true
        especie:
          type: string
          maxLength: 50
        raca:
          type: string
          nullable: true
          maxLength: 100
        data_nascimento:
          type: string
          format: date
          nullable: true
      required:
      - especie
      - id
      - nome
      - tutor
    PetList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        tutor:
          allOf:
          - $ref: '#/components/schemas/TutorBasic'
          readOnly: true
        especie:
          type: string
          maxLength: 50
        raca:
          type: string
          nullable: true
          maxLength: 100
        data_nascimento:
          type: string
          format: date
          nullable: true
      required:
      - especie
      - id
      - nome
      - tutor
    PetSemTutor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        especie:
          type: string
          maxLength: 50
        raca:
          type: string
          nullable: true
          maxLength: 100
        data_nascimento:
          type: string
          format: date
          nullable: true
      required:
      - especie
      - id
      - nome
    RegistroVacinaCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        veterinario:
          type: integer
        vacina:
          type: integer
        pet:
          type: integer
        observacoes:
          type: string
        data:
          type: string
          format: date
      required:
      - id
      - pet
      - vacina
      - veterinario
    RegistroVacinaCreateRequest:
      type: object
      properties:
        veterinario:
          type: integer
        vacina:
          type: integer
        pet:
          type: integer
        observacoes:
          type: string
        data:
          type: string
          format: date
      required:
      - pet
      - vacina
      - veterinario
    RegistroVacinaDetails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        veterinario:
          $ref: '#/components/schemas/VeterinarioBasic'
        vacina:
          $ref: '#/components/schemas/Vacina'
        pet:
          $ref: '#/components/schemas/PetSemTutor'
        observacoes:
          type: string
        data:
          type: string
          format: date
      required:
      - id
      - pet
      - vacina
      - veterinario
    RegistroVacinaList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        veterinario:
          $ref: '#/components/schemas/VeterinarioBasic'
        vacina:
          $ref: '#/components/schemas/Vacina'
        pet:
          $ref: '#/components/schemas/PetBasic'
        data:
          type: string
          format: date
      required:
      - id
      - pet
      - vacina
      - veterinario
    Sucesso:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    TokenRefreshError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    Tutor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        celular:
          type: string
          maxLength: 20
        cpf:
          type: string
          nullable: true
          maxLength: 11
      required:
      - celular
      - id
      - user
    TutorBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/UserBasic'
        celular:
          type: string
          maxLength: 20
        cpf:
          type: string
          nullable: true
          maxLength: 11
      required:
      - celular
      - id
      - user
    TutorCreateRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 150
        first_name:
          type: string
          minLength: 1
          maxLength: 150
        last_name:
          type: string
          minLength: 1
          maxLength: 150
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
          maxLength: 128
        user_id:
          type: integer
        cpf:
          type: string
          minLength: 1
          maxLength: 11
        celular:
          type: string
          minLength: 1
          maxLength: 20
      required:
      - celular
      - cpf
    TutorRequest:
      type: object
      properties:
        celular:
          type: string
          minLength: 1
          maxLength: 20
        cpf:
          type: string
          nullable: true
          minLength: 1
          maxLength: 11
      required:
      - celular
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: Usuário
          description: Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_
            apenas.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: Primeiro nome
          maxLength: 150
        last_name:
          type: string
          title: Último nome
          maxLength: 150
        email:
          type: string
          format: email
          title: Endereço de email
          maxLength: 254
      required:
      - id
      - username
    UserBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: Usuário
          description: Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_
            apenas.
          pattern: ^[\w.@+-]+$
          maxLength: 150
      required:
      - id
      - username
    UserRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          title: Usuário
          description: Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_
            apenas.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: Primeiro nome
          maxLength: 150
        last_name:
          type: string
          title: Último nome
          maxLength: 150
        email:
          type: string
          format: email
          title: Endereço de email
          maxLength: 254
      required:
      - username
    UserWGroups:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: Usuário
          description: Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_
            apenas.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: Primeiro nome
          maxLength: 150
        last_name:
          type: string
          title: Último nome
          maxLength: 150
        email:
          type: string
          format: email
          title: Endereço de email
          maxLength: 254
        groups:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - groups
      - id
      - username
    Vacina:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 120
      required:
      - id
      - nome
    VacinaRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
          maxLength: 120
      required:
      - nome
    Veterinario:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        celular:
          type: string
          maxLength: 20
        crmv:
          type: string
          nullable: true
          maxLength: 20
        cpf:
          type: string
          nullable: true
          maxLength: 11
      required:
      - celular
      - id
      - user
    VeterinarioBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          allOf:
          - $ref: '#/components/schemas/UserBasic'
          readOnly: true
      required:
      - id
      - user
    VeterinarioCreateRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 150
        first_name:
          type: string
          minLength: 1
          maxLength: 150
        last_name:
          type: string
          minLength: 1
          maxLength: 150
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
          maxLength: 128
        user_id:
          type: integer
        cpf:
          type: string
          minLength: 1
          maxLength: 11
        celular:
          type: string
          minLength: 1
          maxLength: 20
        crmv:
          type: string
          minLength: 1
          maxLength: 20
      required:
      - celular
      - cpf
      - crmv
    VeterinarioRequest:
      type: object
      properties:
        celular:
          type: string
          minLength: 1
          maxLength: 20
        crmv:
          type: string
          nullable: true
          minLength: 1
          maxLength: 20
        cpf:
          type: string
          nullable: true
          minLength: 1
          maxLength: 11
      required:
      - celular
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
      description: Autenticação via JWT armazenado em cookies HTTPOnly. Faça login
        em `/api/v1/token/` para obter os tokens automaticamente.
servers:
- url: http://localhost:8000
  description: Servidor local
tags:
- name: accounts
  description: Gerenciamento de usuários e autenticação
- name: veterinarios
  description: Cadastro e gestão de veterinários
- name: tutores
  description: Cadastro e gestão de tutores
- name: pets
  description: Cadastro e gestão de pets
- name: vacinas
  description: Unidades de vacinas disponíveis
- name: registros
  description: Registros de vacinas aplicadas
